#!/usr/bin/env python3
"""
Daily fitness briefing — writes a Markdown note into the Obsidian vault from
FitLocal production data, then git-commits + pushes it. Runs locally via launchd
(see ~/Library/LaunchAgents/com.brendan.fitlocal-briefing.plist).

The training recommendation is generated by a LOCAL LLM (Ollama, qwen3:30b-a3b)
to conserve Anthropic usage, with a deterministic rule-based fallback if Ollama
is down, times out, or returns junk — so the briefing is never blank.

Fetches FitLocal over HTTPS with `curl` (subprocess) deliberately: the system
Python's urllib has no CA bundle on this Mac and fails TLS verification (certifi
gotcha), whereas curl uses the system trust store.

NEXT UP (fitlocal#78): feed the recommendation the PPL rotation (which day is
next) and running history so it's the full coach, not just recovery+load+cut.
"""
import json
import os
import re
import subprocess
import sys
import datetime

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_PATH = os.path.join(REPO, ".env")
BASE = "https://fitlocal-app.fly.dev/api"
# Obsidian vault is a git clone of github.com/breedy231/vault (cross-device sync).
# Kept OUTSIDE iCloud (~/vault, not ~/Documents) so git is the only sync mechanism.
VAULT_REPO = "/Users/brendanreed/vault"
VAULT_DIR = os.path.join(VAULT_REPO, "Notion/Notebook/Personal/Fitness")
LB_PER_KG = 2.2046

OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "qwen3:30b-a3b"   # MoE (3B active) — best speed/quality on this Intel CPU box
OLLAMA_TIMEOUT = 200             # generous: slow on CPU, but this is an unattended background job


def git_sync(repo, filepath, message):
    """Pull latest, stage the note, commit if changed, and push. Best-effort."""
    def run(*args):
        return subprocess.run(["git", "-C", repo, *args], capture_output=True, text=True)
    pull = run("pull", "--rebase", "--autostash")
    if pull.returncode != 0:
        print(f"WARN: git pull failed: {pull.stderr.strip()}", file=sys.stderr)
    run("add", filepath)
    if not run("status", "--porcelain").stdout.strip():
        print("git: no change to commit")
        return
    commit = run("commit", "-m", message)
    if commit.returncode != 0:
        print(f"WARN: git commit failed: {commit.stderr.strip()}", file=sys.stderr)
        return
    push = run("push")
    print("git: pushed" if push.returncode == 0 else f"WARN: git push failed: {push.stderr.strip()}",
          file=sys.stderr if push.returncode != 0 else sys.stdout)


def read_key():
    with open(ENV_PATH) as f:
        for line in f:
            if line.startswith("FITLOCAL_API_KEY="):
                return line.split("=", 1)[1].strip()
    raise SystemExit("FITLOCAL_API_KEY not found in " + ENV_PATH)


def get(path, key):
    """GET {BASE}{path} via curl. Returns parsed JSON, or None on failure."""
    r = subprocess.run(
        ["curl", "-sS", "-m", "25", "-H", f"Authorization: Bearer {key}", BASE + path],
        capture_output=True, text=True,
    )
    if r.returncode != 0 or not r.stdout.strip():
        print(f"WARN: fetch {path} failed: {r.stderr.strip()}", file=sys.stderr)
        return None
    try:
        return json.loads(r.stdout)
    except json.JSONDecodeError:
        print(f"WARN: fetch {path} returned non-JSON", file=sys.stderr)
        return None


def rule_based_recommendation(rec, dl):
    """Deterministic fallback recommendation from recovery + deload flag."""
    if not rec:
        return None
    majors = ["chest", "back", "quads", "hamstrings", "shoulders"]
    avg_major = sum(rec.get(m, 0) for m in majors) / len(majors)
    weak = [m for m, v in rec.items() if v < 50]
    if avg_major > 70 and not weak:
        todo = "Lift — next in your PPL rotation. Majors are recovered."
    else:
        todo = "Easy Zone-2 cardio or rest — major muscles aren't fully recovered."
    caveat = (f" Watch your {', '.join(weak)} "
              f"({', '.join(str(rec[m]) + '%' for m in weak)} recovered) — least-recovered tissue."
              if weak else "")
    deload = " A deload is due." if dl and dl.get("suggest") else ""
    return f"{todo}{caveat}{deload}"


def llm_recommendation(rec, dl, tl, cut_line):
    """Coaching rec from the local LLM. Returns clean prose, or None to trigger fallback."""
    if not rec:
        return None
    recs = ", ".join(f"{m} {v}%" for m, v in sorted(rec.items(), key=lambda x: x[1]))
    load = f"Training load is {tl.get('ratio')}x baseline ({tl.get('label', '?')})." if tl else ""
    deload = "A deload is flagged as due." if dl and dl.get("suggest") else ""
    prompt = (
        "You are Brendan's strength & running coach. Write today's training recommendation.\n\n"
        "His standing goals: (1) build his running — increase distance and consistency, and protect "
        "impact tissue (calves, shins) so he doesn't get injured; (2) perform well while on a "
        "calorie-deficit cut — don't overreach or dig a recovery hole in the deficit.\n\n"
        f"Today's data:\n"
        f"- Muscle recovery (higher = fresher): {recs}\n"
        f"- {load} {deload}\n"
        f"- {cut_line}\n\n"
        "Recommend what to train today and how hard. Decide which muscle groups are recovered enough "
        "to lift, and whether to run / cross-train on the bike / rest given impact-tissue recovery and "
        "the training load. Keep it aligned with the cut.\n\n"
        "Respond with ONLY 2-3 sentences of direct recommendation. Do NOT restate the numbers, do NOT "
        "explain your reasoning, do NOT write a preamble. Start with the recommendation itself.\n\n"
        "/no_think"  # qwen3 directive: disable chain-of-thought (more reliable than the API think flag)
    )
    payload = json.dumps({
        "model": OLLAMA_MODEL, "prompt": prompt, "stream": False, "think": False,
        "options": {"temperature": 0.2, "num_predict": 500},
    })
    r = subprocess.run(
        ["curl", "-sS", "-m", str(OLLAMA_TIMEOUT), OLLAMA_URL, "--data", "@-"],
        input=payload, capture_output=True, text=True,
    )
    if r.returncode != 0 or not r.stdout.strip():
        print(f"WARN: ollama call failed (rc={r.returncode}); using fallback", file=sys.stderr)
        return None
    try:
        text = json.loads(r.stdout).get("response", "")
    except json.JSONDecodeError:
        print("WARN: ollama returned non-JSON; using fallback", file=sys.stderr)
        return None
    # Strip any <think> reasoning (qwen emits it even with think=false sometimes).
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    if "</think>" in text:
        text = text.split("</think>")[-1]
    text = " ".join(text.split()).strip()
    # Strip a leading "Today:" / "Today," the model sometimes echoes (we add our own label).
    text = re.sub(r"^today\s*[:,\-]\s*", "", text, flags=re.IGNORECASE).strip()
    # Sanity gate: reject reasoning-preamble / restated-data / too-short junk.
    low = text.lower()
    if (len(text) < 40
            or low.startswith(("okay", "hmm", "let me", "alright", "first", "so,", "so ", "the user", "we need", "based on the data"))
            or "the user" in low[:120]):
        print("WARN: ollama output failed sanity gate; using fallback", file=sys.stderr)
        return None
    return text


def main():
    key = read_key()
    g = get("/goals", key)
    n = get("/goals/daily-nutrition", key)
    snaps = get("/health-snapshots", key)
    rec_raw = get("/recovery-summary", key)
    dl = get("/deload-check", key)
    tl = get("/training-load", key)

    missing = [name for name, v in
               [("goals", g), ("nutrition", n), ("weights", snaps), ("recovery", rec_raw)]
               if v is None]
    rec = {m["name"]: m["recoveryPct"] for m in rec_raw["muscles"]} if rec_raw else {}

    # Latest logged weight + short trend (current-year rows with a body weight).
    ws = []
    if snaps:
        ws = [s for s in snaps
              if str(s.get("date", "")).startswith(str(datetime.date.today().year))
              and s.get("bodyWeightKg")]
        ws.sort(key=lambda s: s["date"])

    # Compute cut figures up front so the recommendation can reference them.
    cut_block = None
    cut_line = "Cut status unknown."
    weighin_ref = "unknown"
    if ws and g:
        last = ws[-1]
        kg = last["bodyWeightKg"]
        lb = kg * LB_PER_KG
        tgt_lb = g["targetWeightKg"] * LB_PER_KG
        togo = lb - tgt_lb
        trend = " → ".join(f'{s["bodyWeightKg"] * LB_PER_KG:.1f}' for s in ws[-5:])
        cut_block = (f"**Cut:** {lb:.1f} lb ({kg:.2f} kg), **{togo:.1f} lb to go** to target "
                     f"{tgt_lb:.1f} lb. Cut ends {g.get('cutEndDate', '?')}. "
                     f"Recent 5: {trend} lb (single-day swings are water, not fat).")
        cut_line = f"Cut: {lb:.1f} lb, {togo:.1f} lb to target {tgt_lb:.0f} lb, cut ends {g.get('cutEndDate', '?')}."
        weighin_ref = last["date"]

    # Recommendation: local LLM first, deterministic fallback if it fails the gate.
    llm_rec = llm_recommendation(rec, dl, tl, cut_line)
    rec_text = llm_rec or rule_based_recommendation(rec, dl)
    rec_source = f"{OLLAMA_MODEL} (local)" if llm_rec else "rule-based fallback"

    today = datetime.date.today()
    fname = f"Daily Briefing {today.month}-{today.day}-{str(today.year)[2:]}.md"
    lines = [f"# Daily Briefing — {today.strftime('%A, %B %-d, %Y')}", ""]
    if rec_text:
        lines += [f"**Today:** {rec_text}", ""]
    if cut_block:
        lines += [cut_block, ""]

    # Nutrition.
    if g:
        intake = ""
        if n:
            cur = n.get("calories", {}).get("current")
            prot = n.get("protein", {}).get("current")
            intake = (f" Yesterday's logged intake (Apple Health not synced today yet): {cur} cal / {prot}g protein."
                      if n.get("isStale") else f" Today so far: {cur} cal / {prot}g protein.")
        lines += [
            f"**Nutrition:** target **{g['targetCalories']} cal / {g['targetProteinG']:.0f}g protein** "
            f"(maintenance {g['maintenanceCalories']}).{intake}", ""]

    lines += [f"**Weigh-in:** latest log is {weighin_ref} — weigh in this morning if you haven't yet.", ""]
    if missing:
        lines += [f"> ⚠️ Some data was unavailable: {', '.join(missing)}.", ""]
    lines += [f"*Auto-generated from FitLocal prod. Recommendation: {rec_source}.*"]

    os.makedirs(VAULT_DIR, exist_ok=True)
    path = os.path.join(VAULT_DIR, fname)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{datetime.datetime.now().isoformat(timespec='seconds')} wrote {path} [rec: {rec_source}]"
          + (f" (missing: {', '.join(missing)})" if missing else ""))
    git_sync(VAULT_REPO, path, f"Daily briefing {today.month}-{today.day}-{str(today.year)[2:]}")


if __name__ == "__main__":
    main()
